### ISSUE TITLE
VC2015 not recognized

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/Digger#51]
Just tried to bisect a Win64 regression, but Digger doesn't pick up my VC2015 installation, also tried to run it in the VC developer console.

Would be great if it supported the same set as dmd's installer https://github.com/dlang/installer/blob/5179af93d9f0fd84d714e8742492434bf16ed2f6/windows/d2-installer.nsi#L351.
Even better if we could somehow get rid of those VC detections and support any version.

**Comment by CyberShadow** [comment]
Digger does not attempt to use any Visual Studio installs on the host. It always unpacks and installs its own private copy of the necessary components (which it verifies to match a hard-coded hash), in order to get as close to reproducible builds as possible. This has always been the case, maybe you're confusing it with another tool?

**Comment by MartinNowak** [comment]
Ah OK, good to know. Then maybe the installation didn't work or is messed up for some reason.
Or do I have to install it explicitly?

**Comment by CyberShadow** [comment]
No, it should be fully automatic. Is there any indication of what might have went wrong in the console output?

Perhaps try with a fresh workDir as well.

**Comment by MartinNowak** [comment]
Sorry for the noise, works now after I found the `[build] components.dmd.dmdModel = 64` setting for bisect.ini.

**Comment by CyberShadow** [comment]
Ah, that reminds me, I should separate the DMD model from the target (Phobos/Druntime) model. I'll add that to the list for 3.0.
