### ISSUE TITLE
Allow https:// to be used for git repo URLs

### ISSUE THREAD

**Issue by JackStouffer** [CyberShadow/Digger#70]
Many corporate firewalls block `git://` which makes digger unusable.

**Comment by CyberShadow** [comment]
This is caused by a (user-hostile :wink:) configuration at the user site, so I think it should ideally be fixed there. Git provides a simple workaround that will fix this issue globally (for all git usage by the user):

```
git config --global url."https://".insteadOf git://
```

We could detect this situation and suggest this workaround, though it's probably simpler to just switch the URLs to https...

**Comment by JackStouffer** [comment]
Copying from the slack discussion:

Doesn't seem to be working for cloning dmd

It's suck at

```
Submodule 'dmd' (git://github.com/dlang/dmd) registered for path 'dmd'
Cloning into '/Users/Jack/digger/work/repo/dmd'...
```

**Comment by CyberShadow** [comment]
I don't know what could be wrong, sorry. I know that workaround was used with success in the past, so maybe check the process list or network traffic to check if it's really going through HTTPS?

**Comment by CyberShadow** [comment]
> I know that workaround was used with success in the past,

Oops, looks like that only works on Windows, because we tell git to not use the system-wide configuration elsewhere (to ensure it doesn't pollute the build).

d4dad99fc04abc4ffce401e2cb78a160ed66b1d7 adds a new setting that can be used to achieve this.
